brand:
  name: 'Emily Risinger PLLC'
  email: 'help@emilyrisinger.com'
  phone: '612.564.5717'
  intro:
    heading: >
      ERP for OCD and Anxiety Disorders
      Behavioral Interventions for BFRBs and Tourettes
  specialties:
    heading: Specialties
    subheading: Anxiety Disorders Treated
    specialty:
      - heading: OCD
        text: Harm, doubt, contamination, "Just Right, intrusive thoughts
      - heading: BFRBs
        text: Skin Picking, Hair-Pulling, Nail Bitting
      - heading: Tourettes
        text: Vocal and Motor, Simple and Complex
      - heading: Phobias
        text: Social, Emetophobia, Agoraphobia
  services:
    heading: Services
    subheading: Understand Our Role
    service:
      - heading: Individual Counseling
        text: >
          I offer individual therapy for adults. 
          in the treatment of anxiety issues through the use of Cognitive Behavioral Therapy
          (CBT) and Exposure & Response Prevention (ERP). Both CBT and ERP are evidence based
          practices that have been shown to provide strong long term benefits in the treatment
          of anxiety.
      - heading: Cost and Insurance
        text: >
          I offer transparent flat fees for my services: $135 per therapy session.
          Clients are encouraged to confirm out-of-network coverage options
          with their insurance provider; I do not bill insurance payers. Therapy sessions are 45
          minutes. 
  team:
    heading: Meet Our Therapist
    subheading: Learn Who I Am
    members:
      - name: Emily Risinger
        role: MS, ATR, LPCC
        img: img/team/emily-risinger.jpg
        text: >
          Emily works with with adults struggling with OCD, Tourettes and BFRBs. She uses CBT, ERP, ComB
          and Art therapy to support her clients in developing effective coping skills. Knowing
          that accountability is key in treating anxiety she takes a caring but firm approach with
          her clients and their support system.
  connect:
    heading: Book A Provider
    subheading: >
      I am here for you when you need me! Call me to schedule an appointment, or send me
      an email and I’ll get back to you as soon as possible.
nav:
  - title: Specialties
    url: '#specialties'
  - title: Services
    url: '#services'
  - title: About
    url: '#about'
  - title: Connect
    url: '#connect'
copyright: Copyright &copy; Emily Risinger PLLC 2019-2021
quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'
